// <auto-generated />
using EFPostgrsql.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EFPostgrsql.App.Migrations
{
  [DbContext(typeof(ApplicationDbContext))]
  [Migration("20201218122048_InitialDb")]
  partial class InitialDb
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .UseIdentityByDefaultColumns()
          .HasAnnotation("Relational:MaxIdentifierLength", 63)
          .HasAnnotation("ProductVersion", "5.0.1");
#pragma warning restore 612, 618
    }
  }
}
